//
// Created by PengHaiChen on 2023/6/17.
//

#ifndef HIGHPERFORMANCEIMAGEPROCESSING_IMAGEMINPIXELSIZE_H
#define HIGHPERFORMANCEIMAGEPROCESSING_IMAGEMINPIXELSIZE_H

jobject getImageMinPixelSize(JNIEnv *env, jobject pJobject, jobject bitmap);

#endif //HIGHPERFORMANCEIMAGEPROCESSING_IMAGEMINPIXELSIZE_H
